DROP TRIGGER IF EXISTS SB1_BIZIFY_EXP;
GO

CREATE TRIGGER SB1_BIZIFY_EXP
    ON SB1990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (B1_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.B1_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET B1_X2EAXP = ''
        FROM SB1990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS CTD_BIZIFY_EXP;
GO

CREATE TRIGGER CTD_BIZIFY_EXP
    ON CTD990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (CTD_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.CTD_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET CTD_X2EAXP = ''
        FROM CTD990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS CTT_BIZIFY_EXP;
GO

CREATE TRIGGER CTT_BIZIFY_EXP
    ON CTT990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (CTT_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.CTT_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET CTT_X2EAXP = ''
        FROM CTT990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS CTH_BIZIFY_EXP;
GO

CREATE TRIGGER CTH_BIZIFY_EXP
    ON CTH990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (CTH_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.CTH_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET CTH_X2EAXP = ''
        FROM CTH990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SE4_BIZIFY_EXP;
GO

CREATE TRIGGER SE4_BIZIFY_EXP
    ON SE4990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (E4_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.E4_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET E4_X2EAXP = ''
        FROM SE4990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SBM_BIZIFY_EXP;
GO

CREATE TRIGGER SBM_BIZIFY_EXP
    ON SBM990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (BM_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.BM_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET BM_X2EAXP = ''
        FROM SBM990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SA5_BIZIFY_EXP;
GO

CREATE TRIGGER SA5_BIZIFY_EXP
    ON SA5990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (A5_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.A5_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET A5_X2EAXP = ''
        FROM SA5990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO


DROP TRIGGER IF EXISTS SA2_BIZIFY_EXP;
GO

CREATE TRIGGER SA2_BIZIFY_EXP
    ON SA2990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (A2_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.A2_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET A2_X2EAXP = ''
        FROM SA2990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SAH_BIZIFY_EXP;
GO

CREATE TRIGGER SAH_BIZIFY_EXP
    ON SAH990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (AH_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.AH_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET AH_X2EAXP = ''
        FROM SAH990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SF1_BIZIFY_EXP;
GO

CREATE TRIGGER SF1_BIZIFY_EXP
    ON SF1990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (F1_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.F1_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET F1_X2EAXP = ''
        FROM SF1990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SC7_BIZIFY_EXP;
GO

CREATE TRIGGER SC7_BIZIFY_EXP
    ON SC7990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (C7_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.C7_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET C7_X2EAXP = ''
        FROM SC7990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO

DROP TRIGGER IF EXISTS SC1_BIZIFY_EXP;
GO

CREATE TRIGGER SC1_BIZIFY_EXP
    ON SC1990 
    AFTER UPDATE 
AS
SET NOCOUNT ON;
IF UPDATE (C1_MSEXP) 
BEGIN
    DECLARE @REC INT;
    DECLARE @MSEXP VARCHAR(10);
    SELECT @REC = i.R_E_C_N_O_, @MSEXP = i.C1_MSEXP FROM inserted i

    IF (LEN(@MSEXP) = 0)
        BEGIN
        UPDATE s
        SET C1_X2EAXP = ''
        FROM SC1990 AS s
        WHERE s.R_E_C_N_O_ IN(@REC)
    End;
END;

GO
